Team-Hankki/hankki-server

.github/workflows/dev-cd.yml, .github/workflows/dev-ci.yml, Dockerfile-dev
close #1 
- cicd 구축
멀티모듈 도입시 스크립트 조금 수정해야 할 수도
=> [infra] cicd 구축

.github/workflows/dev-cd.yml
close #13 
- 서브모듈의 yml 파일을 resources로 복사해주지 않았음
=> [chore] submodule 도입으로 인한 cd 에러 해결

src/main/java/org/hankki/hankkiserver/auth/config/SecurityConfig.java
close #25 
- CD 오류 해결
Whitelist에 api 추가 했습니다.
=> [fix] add whiteList

build.gradle
close #28 
- redis 의존성 삭제
build gradle에 redis 의존성 삭제했습니다.
=> [fix] redis 의존성 삭제

src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java, src/main/java/org/hankki/hankkiserver/api/store/parameter/PriceCategory.java, src/main/java/org/hankki/hankkiserver/api/store/parameter/SortOption.java, src/main/java/org/hankki/hankkiserver/api/store/service/StoreQueryService.java, src/main/java/org/hankki/hankkiserver/api/store/service/response/CategoriesResponse.java, src/main/java/org/hankki/hankkiserver/api/store/service/response/CategoryResponse.java, src/main/java/org/hankki/hankkiserver/api/store/service/response/PriceCategoriesResponse.java, src/main/java/org/hankki/hankkiserver/api/store/service/response/PriceCategoryResponse.java, src/main/java/org/hankki/hankkiserver/api/store/service/response/SortOptionResponse.java, src/main/java/org/hankki/hankkiserver/api/store/service/response/SortOptionsResponse.java, src/main/java/org/hankki/hankkiserver/api/university/controller/UniversityController.java, src/main/java/org/hankki/hankkiserver/api/university/service/UniversityFinder.java, src/main/java/org/hankki/hankkiserver/api/university/service/UniversityQueryService.java, src/main/java/org/hankki/hankkiserver/api/university/service/response/UniversitiesResponse.java, src/main/java/org/hankki/hankkiserver/api/university/service/response/UniversityFindResponse.java, src/main/java/org/hankki/hankkiserver/domain/common/Point.java, src/main/java/org/hankki/hankkiserver/domain/store/model/StoreCategory.java
close #41 
- 종류 응답의 경우 추후 사진 추가, 상수마다 이미지 url을 지정 필요.
=> [feat] 대학, 종류, 가격대, 정렬 드롭다운 정보조회 api 생성

src/main/java/org/hankki/hankkiserver/external/openfeign/apple/ApplePublicKeyGenerator.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/dto/ApplePublicKey.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/dto/ApplePublicKeys.java
close #61 
- key값을 받아오지 못하는 오류 발생했는데 변수명이 문제였던 것 같습니다.
제발 돌아갔으면 좋겠어요.
=> [fix] 애플 로그인 문제 해결하기

src/main/java/org/hankki/hankkiserver/domain/store/model/Store.java
close #76 
- 빌드 에러 고침
- yml 파일 확인 완료
- postman test 완료
rebase하면서 충돌 해결하는 과정에서 오류가 있었던 것 같습니다..
연관된 부분 TEST 결과
<가게 단일 조회>
<족보 단일 조회>
=> [fix] 빌드 에러 fix

src/main/java/org/hankki/hankkiserver/api/external/service/response/LocationResponse.java
close #89 
- 검색 api의 결과로 태그가 나가는 오류 수정
=> [fix] 식당 검색 api 응답 결과 수정

src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java
close #99 
- Get 요청을 Post 요청으로 변경하였습니다.
빌드 및 api 테스트 완료했습니다.
=> [fix] Get 요청 -> Post 요청으로 수정

src/main/java/org/hankki/hankkiserver/api/advice/GlobalExceptionHandler.java
close #101 
- 상세한 에러 확인을 위해 Exception의 클래스와 stackTrace를 출력하도록 했습니다.
=> [feat] 500에러 로그 포맷 변경

src/main/java/org/hankki/hankkiserver/api/favorite/service/response/FavoriteStoreFindResponse.java, src/main/java/org/hankki/hankkiserver/domain/store/model/Store.java
close #107
- S3 연동으로 store 디폴트 이미지 리턴 방식 수정
=> [refac] S3 연동으로 store 디폴트 이미지 리턴 방식 수정

src/main/java/org/hankki/hankkiserver/api/user/controller/request/UserUniversityPostRequest.java
close #109 
- 사용자 대학교 설정 정보 생성 API valid 검증 추가
3~20으로 추가했습니다.
=> [feat] 사용자 대학교 설정 정보 생성 API valid 검증 추가

src/main/java/org/hankki/hankkiserver/domain/ImageInjector.java, src/main/java/org/hankki/hankkiserver/domain/user/ImageSelector.java, src/main/java/org/hankki/hankkiserver/domain/user/model/UserInfo.java
close #85 
- 사용자 프로필을 랜덤으로 설정하는 로직입니다.
`@Value` 어노테이션을 사용해서 관리를 하려니 위와 같은 코드 밖에 떠오르지 않습니다. 다른 더 좋은 방법이 있는지 같이 고민해주세욤...
=> [feat] 프로필 이미지 랜덤으로 설정하기

src/main/java/org/hankki/hankkiserver/domain/store/model/StoreCategory.java, src/main/java/org/hankki/hankkiserver/domain/store/model/StoreCategoryImageInjector.java
close #114 
- 가게 카테고리 이미지 URL yml에 등록
- 빈 생성 후 주입
=> [feat] 가게 카테고리 이미지 

src/main/java/org/hankki/hankkiserver/HankkiserverApplication.java, src/main/java/org/hankki/hankkiserver/api/advice/ResponseAdvice.java, src/main/java/org/hankki/hankkiserver/api/favorite/controller/FavoriteController.java, src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteDeleter.java, src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteQueryService.java, src/main/java/org/hankki/hankkiserver/api/favorite/service/command/FavoriteStoreDeleteCommand.java, src/main/java/org/hankki/hankkiserver/api/favorite/service/command/FavoriteStorePostCommand.java, src/main/java/org/hankki/hankkiserver/api/favorite/service/response/FavoriteGetResponse.java, src/main/java/org/hankki/hankkiserver/api/favoritestore/service/FavoriteStoreDeleter.java, src/main/java/org/hankki/hankkiserver/api/favoritestore/service/FavoriteStoreFinder.java, src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java, src/main/java/org/hankki/hankkiserver/api/store/controller/request/StorePostRequest.java, src/main/java/org/hankki/hankkiserver/api/store/parameter/PriceCategory.java, src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java, src/main/java/org/hankki/hankkiserver/api/store/service/response/StoreDuplicateErrorResponse.java, src/main/java/org/hankki/hankkiserver/api/store/service/response/StorePinsResponse.java, src/main/java/org/hankki/hankkiserver/api/store/service/response/StoreResponse.java, src/main/java/org/hankki/hankkiserver/api/university/service/UniversityFinder.java, src/main/java/org/hankki/hankkiserver/api/user/controller/request/UserUniversityPostRequest.java, src/main/java/org/hankki/hankkiserver/api/user/service/response/UserStoreReportedResponse.java, src/main/java/org/hankki/hankkiserver/api/user/service/response/UserStoresReportedGetResponse.java, src/main/java/org/hankki/hankkiserver/api/user/service/response/UserUniversityFindResponse.java, src/main/java/org/hankki/hankkiserver/auth/filter/JwtAuthenticationFilter.java, src/main/java/org/hankki/hankkiserver/auth/jwt/JwtValidator.java, src/main/java/org/hankki/hankkiserver/common/code/AuthErrorCode.java, src/main/java/org/hankki/hankkiserver/common/code/CommonSuccessCode.java, src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreRepository.java, src/main/java/org/hankki/hankkiserver/domain/user/repository/UserRepository.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/dto/ApplePublicKeys.java, src/main/java/org/hankki/hankkiserver/external/openfeign/kakao/KakaoFeignClient.java
close #122 
- 안쓰는 import문들 다 삭제 했습니다.
안쓰는 함수는 혹시 몰라서 남겨놨습니다.
=> [refac] 안쓰는 import문 삭제

src/main/java/org/hankki/hankkiserver/api/auth/service/AuthService.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/AppleClientSecretGenerator.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/AppleFeignClient.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/AppleOAuthProvider.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/dto/AppleTokenResponse.java
close #126 
- yml 파일과 feign으로 데이터 받아오는 과정에서 형식이 일치하지 않는 것을 발견해서 수정했습니다.
=> [fix] 애플 회원 탈퇴 오류 수정

src/main/java/org/hankki/hankkiserver/api/auth/service/AuthService.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/dto/AppleTokenResponse.java
close #131 
- 오류 발생 원인을 찾기 위한 로그 찍기
=> [feat] 애플 회원 탈퇴 오류 로그 확인

src/main/java/org/hankki/hankkiserver/api/auth/service/AuthService.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/AppleClientSecretGenerator.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/AppleFeignClient.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/AppleOAuthProvider.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/ApplePrivateKeyGenerator.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/dto/AppleRevokeRequest.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/dto/AppleTokenRequest.java, src/main/java/org/hankki/hankkiserver/external/openfeign/apple/dto/AppleTokenResponse.java
close #134 
- reponse 응답 순서와 clientSecret 함수 위치만 살짝 바꿨습니다.
=> [Fix] 애플 로그인 (회원탈퇴) 오류 수정

src/main/java/org/hankki/hankkiserver/api/auth/service/AuthService.java, src/main/java/org/hankki/hankkiserver/api/auth/service/UserFinder.java, src/main/java/org/hankki/hankkiserver/domain/menu/model/Menu.java, src/main/java/org/hankki/hankkiserver/domain/user/model/User.java, src/main/java/org/hankki/hankkiserver/domain/user/model/UserStatus.java, src/main/java/org/hankki/hankkiserver/domain/user/repository/UserRepository.java
close #119 
- user field 이름 변경
- menu generation type추가
=> [refac] 엔티티 필드 이름 변경 및 generation strategy 추가

src/main/java/org/hankki/hankkiserver/api/auth/service/UserFinder.java, src/main/java/org/hankki/hankkiserver/domain/user/repository/UserRepository.java
=> [fix] user 필드 이름 변경으로 인한 repository 오류 수정

src/main/java/org/hankki/hankkiserver/api/favorite/service/response/FavoriteStoreResponse.java, src/main/java/org/hankki/hankkiserver/api/user/service/response/UserStoreReportedResponse.java, src/main/java/org/hankki/hankkiserver/domain/store/model/Store.java
close #159 
- 족보 상세보기에서 image_url 필드 null일 경우 null 반환
- 테스트 완료
```json
{
"code": 200,
"message": "요청이 성공했습니다(200).",
"data": {
"title": "title2",
"details": [
"#김지혜",
"#김지혜"
],
"stores": [
{
"id": 1,
"name": "한스친친 광운대점",
"imageUrl": null,
"category": "중식",
"lowestPrice": 6000,
"heartCount": 0
},
{
"id": 2,
"name": "더원",
"imageUrl": null,
"category": "중식",
"lowestPrice": 6000,
"heartCount": 0
},
{
"id": 3,
"name": "마떡",
"imageUrl": null,
"category": "분식",
"lowestPrice": 3000,
"heartCount": 0
},
{
"id": 4,
"name": "사계절김밥",
"imageUrl": "https://hankki-jokbo.s3.ap-northeast-2.amazonaws.com/dummy/%E1%84%80%E1%85%AA%E1%86%BC%E1%84%8B%E1%85%AE%E1%86%AB%E1%84%83%E1%85%A2_%E1%84%89%E1%85%A1%E1%84%80%E1%85%A8%E1%84%8C%E1%85%A5%E1%86%AF%E1%84%80%E1%85%B5%E1%86%B7%E1%84%87%E1%85%A1%E1%86%B8.jpeg", …
```
=> [fix] 족보 상세보기 API image_url 필드 null일 경우 null 반환

src/main/java/org/hankki/hankkiserver/api/user/service/response/UserHeartedStoreListResponse.java, src/main/java/org/hankki/hankkiserver/api/user/service/response/UserHeartedStoreViewResponse.java, src/main/java/org/hankki/hankkiserver/domain/heart/repository/HeartRepository.java
close #160 
- imageUrl default값에서 null값으로 응답을 보내도록 변경했습니다.
API 테스트 완료
=> [fix] 기본 이미지 정책 변경에 따른 좋아요 식당 목록 조희 api 수정

src/main/java/org/hankki/hankkiserver/domain/report/repository/ReportRepository.java
close #164 
- 내가 제보한 식당에서 이미지 없으면 안가져오는 문제 fix
내가 제보한 식당에서 이미지 없으면 안가져오는 문제 fix
=> [fix] 내가 제보한 식당에서 이미지 없으면 안가져오는 문제 fix

src/main/java/org/hankki/hankkiserver/api/user/controller/request/UserUniversityPostRequest.java, src/main/java/org/hankki/hankkiserver/api/user/service/response/UserUniversityFindResponse.java
close #171 
- notion에 redis갖고 조금 끄적여봤습니다. 궁금하시다면 거기에 적어놓았습니다..
=> [fix] 사용자 대학교 미설정 가능하도록 변경

src/main/java/org/hankki/hankkiserver/api/university/controller/UniversityController.java, src/main/java/org/hankki/hankkiserver/api/university/service/UniversityFinder.java, src/main/java/org/hankki/hankkiserver/api/university/service/UniversityQueryService.java, src/main/java/org/hankki/hankkiserver/domain/university/repository/UniversityRepository.java
=> [fix] 대학교 조회시 name기준 오름차순 정렬하도록 변경

src/main/java/org/hankki/hankkiserver/api/user/controller/request/UserUniversityPostRequest.java
close #175 
- useruniversitypostrequest 의 name min 2로 변경
=> [fix] 유저 대학교 설정 api 검증 조건 변경

src/main/java/org/hankki/hankkiserver/api/store/service/StoreCommandService.java, src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java, src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreRepository.java
close #177 
- 식당 생성시 예외처리 조건을 위치 검증조건과 통일시켰습니다. **위경도 이름 삭제여부**로 판단합니다.
=> [fix] 식당 생성시 예외처리 조건 수정

.github/workflows/prod-cd.yml, .github/workflows/prod-ci.yml, Dockerfile-prod
close #180 
- application-prod.yml 생성
- workflow files 생성
- dockerfile-prod생성
기존 yml 파일에서 사용하지 않는 설정들 몇개 지웠습니다.
=> [feat] dev, prod 서버 분리

src/main/java/org/hankki/hankkiserver/api/store/service/StoreCommandService.java
=> [fix] cd 오류 수정

src/main/java/org/hankki/hankkiserver/api/advice/GlobalExceptionHandler.java, src/main/java/org/hankki/hankkiserver/common/code/BusinessErrorCode.java
close #184 
- 400으로 나와야 하는 에러중 exception handler에서 처리하지 않아 500으로 뜨는 경우 해결
=> [feat] exception handler에 예외 추가

.github/workflows/prod-cd.yml
close #192 
-  오타로 인해 prod 에서 dev환경으로 계속 돌아가서 오류가 난거였음..
개멍청하다 진짜
=> [fix] prod-cd.yml 오타수정

src/main/java/org/hankki/hankkiserver/api/store/service/response/MenuResponse.java
close #199
-  menu crud에 필요한 menu id 반환
=> [fix] 식당 세부조회 응답 변경

src/main/java/org/hankki/hankkiserver/auth/config/SecurityConfig.java
close #203 
- 둘러보기가 필요해짐에 따라 허용할 api 목록 추가했습니다.
- 개인화된 api중 둘러보기가 허용된 것이 없어 @UserId에서 분기처리하는 로직은 넣지 않았습니다.
=> [feat] 둘러보기 추가를 위한 whiteList 추가

build.gradle, src/main/java/org/hankki/hankkiserver/api/auth/service/AuthService.java, src/main/java/org/hankki/hankkiserver/api/external/service/DiscordEventListener.java, src/main/java/org/hankki/hankkiserver/api/external/service/DiscordService.java, src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java, src/main/java/org/hankki/hankkiserver/api/store/service/StoreCommandService.java, src/main/java/org/hankki/hankkiserver/api/store/service/command/StoreDeleteCommand.java, src/main/java/org/hankki/hankkiserver/event/EventPublisher.java, src/main/java/org/hankki/hankkiserver/event/EventPublisherAdapter.java, src/main/java/org/hankki/hankkiserver/event/store/CreateStoreEvent.java, src/main/java/org/hankki/hankkiserver/event/store/DeleteStoreEvent.java, src/main/java/org/hankki/hankkiserver/event/user/CreateUserEvent.java, src/main/java/org/hankki/hankkiserver/external/openfeign/discord/DiscordFeignClient.java, src/main/java/org/hankki/hankkiserver/external/openfeign/discord/dto/DiscordMessage.java
* [feat] create discord feign client
* [feat] create DiscordService
* [feat] create eventpublisher interface and impl
* [feat] create discord event listener
* [feat] add event publisher in logic
* [feat] add discord webhook in yml
* [refac] refactor parameters
* [refac] delete unused import statement
* [refac] fix typo
* [feat] add userid to discord message on store delete
* [chore] add gitignore
* [dependency] add discord appender dependency
* [feat] change EventListener to TransactionalEventListener
* [dependency] edit build.gradle
close #<issue_num>
-
=> [feat] 디스코드 알람 (#206)

src/main/java/org/hankki/hankkiserver/api/menu/service/response/MenusPostResponse.java
=> [refac] DTO 이름 통일

src/main/java/org/hankki/hankkiserver/api/advice/GlobalExceptionHandler.java, src/main/java/org/hankki/hankkiserver/api/menu/controller/MenuController.java, src/main/java/org/hankki/hankkiserver/api/menu/service/DeletedMenuUpdater.java, src/main/java/org/hankki/hankkiserver/api/menu/service/MenuCommandService.java, src/main/java/org/hankki/hankkiserver/api/menu/service/MenuFinder.java, src/main/java/org/hankki/hankkiserver/api/menu/service/command/MenuDeleteCommand.java, src/main/java/org/hankki/hankkiserver/api/menu/service/response/MenuGetResponse.java, src/main/java/org/hankki/hankkiserver/api/menu/service/response/MenusGetResponse.java, src/main/java/org/hankki/hankkiserver/api/menu/service/response/MenusPostResponse.java, src/main/java/org/hankki/hankkiserver/api/store/service/StoreUpdater.java, src/main/java/org/hankki/hankkiserver/api/university/controller/UniversityController.java, src/main/java/org/hankki/hankkiserver/api/university/controller/request/UniversitiesPostRequest.java, src/main/java/org/hankki/hankkiserver/api/university/service/UniversityCommandService.java, src/main/java/org/hankki/hankkiserver/api/university/service/UniversityUpdater.java, src/main/java/org/hankki/hankkiserver/api/university/service/command/UniversitiesPostCommand.java, src/main/java/org/hankki/hankkiserver/domain/menu/model/DeletedMenu.java, src/main/java/org/hankki/hankkiserver/domain/menu/repository/DeletedMenuRepository.java, src/main/java/org/hankki/hankkiserver/domain/menu/repository/MenuRepository.java, src/main/java/org/hankki/hankkiserver/domain/university/model/University.java
=> [feat] 운영 서버 배포

src/main/java/org/hankki/hankkiserver/api/favorite/controller/FavoriteController.java, src/main/java/org/hankki/hankkiserver/api/favorite/controller/request/FavoriteSharedPostRequest.java, src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteCommandService.java, src/main/java/org/hankki/hankkiserver/api/favorite/service/command/FavoriteSharedPostCommand.java, src/main/java/org/hankki/hankkiserver/api/favoritestore/service/FavoriteStoreFinder.java, src/main/java/org/hankki/hankkiserver/domain/favoritestore/repository/FavoriteStoreRepository.java
close #226 
- 족보를 공유하는 기능을 구현했습니다.
- 로컬 DB 테스트 완료
로직
1. 유저가 직접 자신의 제목, 해시태그를 입력함.
2. 이렇게 입력받은 정보로 족보 생성, 여기에 공유받은 족보의 가게 정보를 복사함 - 공유받은 족보로부터 완전히 독립된 족보임'
- 아래 쿼리는 공유받은 족보에 식당이 7개 있을 경우입니다. insert문 총 8개 나감. (족보 + 족보에 포함된 식당)
```sql
Hibernate: 
select
f1_0.favorite_id,
f1_0.created_at,
f1_0.detail,
f1_0.image_type,
f1_0.name,
f1_0.updated_at,
f1_0.user_id 
from
favorite f1_0 
where
f1_0.name=? 
and f1_0.user_id=?
Hibernate: 
insert 
into
favorite
(created_at, detail, image_type, name, updated_at, user_id) 
values
(?, ?, ?, ?, ?, ?) 
returning favorite_id
Hibernate: 
select
fs1_0.favorite_store_id,
fs1_0.favorite_id,
fs1_0.store_id 
from
favorite_store fs1_0 
where
fs1_0.favorite_id=?
Hibernate: 
insert 
into
favorite_store
(favorite_id, store_id) 
values
(?, ?) 
returning …
```
=> [feat] 족보 공유하기 기능 구현 

src/main/java/org/hankki/hankkiserver/domain/store/model/StoreCategory.java, src/main/java/org/hankki/hankkiserver/domain/store/model/StoreCategoryImageInjector.java
=> [feat] 전체 카테고리 추가

src/main/java/org/hankki/hankkiserver/api/store/service/response/StoreGetResponse.java
=> [feat] 식당 상세조회 반환 스펙 변경

src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java, src/main/java/org/hankki/hankkiserver/api/store/service/StoreQueryService.java
=> [feat] 식당 카테고리 api 버저닝

src/main/java/org/hankki/hankkiserver/api/auth/service/AuthFacade.java, src/main/java/org/hankki/hankkiserver/api/auth/service/AuthService.java, src/main/java/org/hankki/hankkiserver/auth/jwt/JwtProvider.java
=> [feat] Refresh Token Rotation 적용 

build.gradle
=> [hotfix] add missing dependency

build.gradle
=> [hotfix] 의존성 추가
