- src/main/java/org/hankki/hankkiserver/domain/common/BaseCreatedAtEntity.java
- src/main/java/org/hankki/hankkiserver/domain/common/BaseTimeEntity.java
- src/main/java/org/hankki/hankkiserver/domain/common/Point.java
- src/main/java/org/hankki/hankkiserver/domain/config/JpaAuditingConfig.java
- src/main/java/org/hankki/hankkiserver/domain/favorite/model/Favorite.java
- src/main/java/org/hankki/hankkiserver/domain/favorite/repository/FavoriteRepository.java
- src/main/java/org/hankki/hankkiserver/domain/favoritestore/model/FavoriteStore.java
- src/main/java/org/hankki/hankkiserver/domain/favoritestore/repository/FavoriteStoreRepository.java
- src/main/java/org/hankki/hankkiserver/domain/heart/model/Heart.java
- src/main/java/org/hankki/hankkiserver/domain/heart/repository/HeartRepository.java
- src/main/java/org/hankki/hankkiserver/domain/menu/model/Menu.java
- src/main/java/org/hankki/hankkiserver/domain/menu/repository/MenuRepository.java
- src/main/java/org/hankki/hankkiserver/domain/report/model/Report.java
- src/main/java/org/hankki/hankkiserver/domain/report/repository/ReportRepository.java
- src/main/java/org/hankki/hankkiserver/domain/store/model/Store.java
- src/main/java/org/hankki/hankkiserver/domain/store/model/StoreCategory.java
- src/main/java/org/hankki/hankkiserver/domain/store/model/StoreImage.java
- src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreImageRepository.java
- src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreRepository.java
- src/main/java/org/hankki/hankkiserver/domain/university/model/University.java
- src/main/java/org/hankki/hankkiserver/domain/university/repository/UniversityRepository.java
- src/main/java/org/hankki/hankkiserver/domain/universitystore/model/UniversityStore.java
- src/main/java/org/hankki/hankkiserver/domain/universitystore/repository/UniversityStoreRepository.java
- src/main/java/org/hankki/hankkiserver/domain/user/model/MemberStatus.java
- src/main/java/org/hankki/hankkiserver/domain/user/model/Platform.java
- src/main/java/org/hankki/hankkiserver/domain/user/model/User.java
- src/main/java/org/hankki/hankkiserver/domain/user/model/UserInfo.java
- src/main/java/org/hankki/hankkiserver/domain/user/model/UserRole.java
- src/main/java/org/hankki/hankkiserver/domain/user/repository/UserInfoRepository.java
- src/main/java/org/hankki/hankkiserver/domain/user/repository/UserRepository.java
close #4 
- user 테이블과 user_info 테이블 간의 외래키 위치 문제에 대한 고민이 있습니다. 현재는 user_info의 정보에 접근하는 일이 빈번할 것 같아, user에서 user_info를 참조할 수 있게 usertable에 외래키를 두었습니다. 외래키 위치에 대한 의견 받습니당
> [feat]  database 초기 엔티티 구성 및 개발

- README.md
> [docs] create readme

- build.gradle
- src/main/java/org/hankki/hankkiserver/api/user/controller/UserController.java
- src/main/java/org/hankki/hankkiserver/api/user/controller/request/UserUniversityPostRequest.java
- src/main/java/org/hankki/hankkiserver/api/user/service/UserCommandService.java
- src/main/java/org/hankki/hankkiserver/api/user/service/UserQueryService.java
- src/main/java/org/hankki/hankkiserver/api/user/service/UserUniversityDeleter.java
- src/main/java/org/hankki/hankkiserver/api/user/service/UserUniversityFinder.java
- src/main/java/org/hankki/hankkiserver/api/user/service/UserUniversityUpdater.java
- src/main/java/org/hankki/hankkiserver/api/user/service/command/UserUniversityPostCommand.java
- src/main/java/org/hankki/hankkiserver/api/user/service/response/UserUniversityFindResponse.java
- src/main/java/org/hankki/hankkiserver/common/code/UserUniversityErrorCode.java
- src/main/java/org/hankki/hankkiserver/domain/user/model/UserUniversity.java
- src/main/java/org/hankki/hankkiserver/domain/user/repository/UserUniversityRepository.java
close #37 
- deploy.sh 내에
```shell
redis_status=$(echo $response | jq -r '.components.redis.status')
if [ "$redis_status" == "DOWN" ]; then
echo "> Redis 상태가 DOWN입니다. docker-compose up -d 실행"
docker-compose up -d
fi
```
추가하여 redis가 다운일때만 docker-compose up -d 실행하도록 했습니다.
- ec2 루트 디렉토리에 docker-compose.yml 추가
```
services:
redis:
container_name: redis
image: redis:alpine
hostname: redis
ports:
- "6379:6379"
networks:
- wascomposenet
networks:
wascomposenet:
external: true
```
- `docker network create wascomposenet` 실행하여 
Docker에서 사용자 정의 네트워크를 생성
wascomposenet을 사용해 컨테이너 간의 통신 가능하게 함
> [feat] redis 의존성 추가 및 유저의 대학교 설정 정보 저장 및 조회 api 생성

- src/main/java/org/hankki/hankkiserver/api/report/controller/ReportController.java
- src/main/java/org/hankki/hankkiserver/api/report/service/ReportFinder.java
- src/main/java/org/hankki/hankkiserver/api/report/service/ReportQueryService.java
- src/main/java/org/hankki/hankkiserver/api/report/service/ReportService.java
- src/main/java/org/hankki/hankkiserver/api/report/service/response/ReportServiceResponse.java
close #30 
- 조회수 조회 api 입니다.
딱히 예외가 발생할만한 상황이 없는 것 같아 예외처리는 하지 않았습니다.
> [feat] 조회수 조희 API

- src/main/java/org/hankki/hankkiserver/api/auth/service/AuthService.java
- src/main/java/org/hankki/hankkiserver/auth/JwtAuthenticationEntryPoint.java
- src/main/java/org/hankki/hankkiserver/auth/filter/JwtAuthenticationFilter.java
- src/main/java/org/hankki/hankkiserver/auth/jwt/JwtGenerator.java
- src/main/java/org/hankki/hankkiserver/auth/jwt/JwtProvider.java
- src/main/java/org/hankki/hankkiserver/auth/jwt/JwtValidator.java
- src/main/java/org/hankki/hankkiserver/common/exception/UnauthorizedException.java
close #44 
accessToken claims에 role 추가해서 role 존재 여부로 refreshToken과 accessToken을 구분하였습니다. 
filter chain을 bean으로 등록하지 않았기에 WhiteList에 등록된 url은 필터를 거치지 않음 -> 때문에 reissue api의 경우 white list에 등록을 해두었기 때문에 따로 filter에서 refreshToken으로 요청이 들어왔을 때 해당 request api가 reissue api인지 검증하는 로직은 제외하였습니다. 즉, refresh Token으로 들어오는 모든 요청에 대해서 예외를 던졌습니다. 
---
또한 비밀키를 인코딩하는 로직에 오류가 있어서 이 또한 수정했습니다. 
(이 과정에서 yml 파일이 조금 바뀌었습니다. submodule update 해주세요)
yml 파일 업데이트 되었습니다.
> [fix] 소셜 로그인 오류 수정

- src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java
- src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java
- src/main/java/org/hankki/hankkiserver/api/store/service/StoreQueryService.java
- src/main/java/org/hankki/hankkiserver/api/store/service/response/StoreThumbnailResponse.java
- src/main/java/org/hankki/hankkiserver/common/code/StoreErrorCode.java
- src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreRepository.java
close #46 
- 식당 썸네일 조회 api입니다.
- 식당의 pk를 받으면 식당의 썸네일 생성에 필요한 정보를 반환합니다.
- soft delete 되지 않은 식당의 정보만 보여줍니다.
- soft delete 여부를 쿼리에 작성했습니다.
- 일단 soft delete여부 상관 없이 갖고 온 후, was에서 soft deleted면 exception을 던질까 아니면 쿼리 자체에서 soft deleted된 가게는 갖고오지 않을지 고민중입니다. 의견 주세요
> [feat] 식당 썸네일 조회 api 생성

- src/main/java/org/hankki/hankkiserver/api/auth/controller/AuthController.java
- src/main/java/org/hankki/hankkiserver/api/auth/service/AuthService.java
- src/main/java/org/hankki/hankkiserver/domain/user/model/User.java
- src/main/java/org/hankki/hankkiserver/external/openfeign/apple/AppleOAuthProvider.java
- src/main/java/org/hankki/hankkiserver/external/openfeign/kakao/KakaoFeignClient.java
- src/main/java/org/hankki/hankkiserver/external/openfeign/kakao/KakaoOAuthProvider.java
- src/main/java/org/hankki/hankkiserver/external/openfeign/kakao/dto/KakaoUnlinkRequest.java
close #48 
- 회원 탈퇴할 때 카카오 서버와 연결 끊는 작업 추가했습니다.
https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#unlink
위의 링크 참고 했습니다
> [refac] 회원 탈퇴 시 카카오 서버와 연결 끊기

- src/main/java/org/hankki/hankkiserver/api/advice/GlobalExceptionHandler.java
- src/main/java/org/hankki/hankkiserver/api/external/controller/ExternalController.java
- src/main/java/org/hankki/hankkiserver/api/external/controller/OpenApiController.java
- src/main/java/org/hankki/hankkiserver/api/external/service/ExternalService.java
- src/main/java/org/hankki/hankkiserver/api/external/service/OpenApiService.java
- src/main/java/org/hankki/hankkiserver/api/external/service/response/LocationResponse.java
- src/main/java/org/hankki/hankkiserver/api/external/service/response/LocationsResponse.java
- src/main/java/org/hankki/hankkiserver/common/code/BusinessErrorCode.java
- src/main/java/org/hankki/hankkiserver/external/openfeign/naver/NaverFeignClient.java
- src/main/java/org/hankki/hankkiserver/external/openfeign/naver/dto/NaverLocationInfo.java
- src/main/java/org/hankki/hankkiserver/external/openfeign/naver/dto/NaverLocationsDto.java
close #56 
- feign client를 사용하여 네이버 api를 연결하였습니다.
- 좌표 스펙을 맞추기 위해 간단한 연산을 추가하고 api에 맞게 응답 구조를 변경했습니다.
> [feat] 식당 검색을 위한 네이버 검색 api 연결

- src/main/java/org/hankki/hankkiserver/api/menu/service/MenuFinder.java
- src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java
- src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java
- src/main/java/org/hankki/hankkiserver/api/store/service/StoreQueryService.java
- src/main/java/org/hankki/hankkiserver/api/store/service/response/MenuResponse.java
- src/main/java/org/hankki/hankkiserver/api/store/service/response/StoreGetResponse.java
- src/main/java/org/hankki/hankkiserver/api/store/service/response/StoreThumbnailResponse.java
- src/main/java/org/hankki/hankkiserver/domain/menu/repository/MenuRepository.java
- src/main/java/org/hankki/hankkiserver/domain/store/model/Store.java
- src/main/java/org/hankki/hankkiserver/domain/store/model/StoreImage.java
- src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreRepository.java
close #50 
- <img width="326" alt="스크린샷 2024-07-12 오전 10 08 01" src="https://github.com/user-attachments/assets/94cbb451-d8d8-484e-acfd-42f0f7ddc4dc">
- <img width="332" alt="스크린샷 2024-07-12 오전 10 09 11" src="https://github.com/user-attachments/assets/e54fa0a4-4b62-42f0-9afa-447c71efcbf7">
- 기존에는 jpql을 사용하여 dto로 바로 받아오려 했지만..
현재 응답 구조가 dto안에 dto가 있는 구조여서 dto로 받아오지 못했습니다..(되나 안 되나 앱잼 이후 확인 필요)
그래서 
store, heart(일대다)를 fetch join하여 가져 온 후 식당정보, 좋아요 여부에 대한 정보 추출,
menu table 조회 후 메뉴 응답 리스트 생성,
storeImage를 조회하여 사진 리스트 생성하여 반환했습니다.
@Batch를 사용할까 하기도 했지만.. 어차피 같은 수의 쿼리가 나가게 되어 현재 로직으로 결정했습니다.
+ dto 생성 메서드에 관한 의견이 궁금합니다.. dto에서 변환 로직을 빼고 싶어서 현재 4개의 매개변수를 사용하는데.. 개선할 방법이 있을까요?
> [feat] 식당 세부 정보 조회 api 

- src/main/java/org/hankki/hankkiserver/api/favorite/controller/FavoriteController.java
- src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteQueryService.java
- src/main/java/org/hankki/hankkiserver/api/favorite/service/command/FavoriteGetCommand.java
- src/main/java/org/hankki/hankkiserver/api/favorite/service/response/FavoriteFindResponse.java
- src/main/java/org/hankki/hankkiserver/api/favorite/service/response/FavoriteStoreFindResponse.java
- src/main/java/org/hankki/hankkiserver/domain/favorite/model/Favorite.java
- src/main/java/org/hankki/hankkiserver/domain/store/model/Store.java
close #27 
-  족보 상세조회 API
- Batch 사용 -> 필드에 어노테이션 생성
Postman test 완료(아래 쿼리 실행 결과) 
- 하이버네이트 6.2부터 `in` 대신에 `array_contains` 를 사용한다고 합니다. postgresql 문법에 맞춰서 `any`로 나가는 것 같습니다.
- Favorite ->  FavoriteStore -> Stroe -> StoreImage 순으로 탐색
```sql
Hibernate: 
select
f1_0.favorite_id,
f1_0.created_at,
f1_0.detail,
f1_0.name,
f1_0.updated_at,
f1_0.user_id 
from
favorite f1_0 
where
f1_0.favorite_id=?
Hibernate: 
select
fs1_0.favorite_id,
fs1_0.favorite_store_id,
s1_0.store_id,
s1_0.category,
s1_0.created_at,
s1_0.heart_count,
s1_0.is_deleted,
s1_0.lowest_price,
s1_0.name,
s1_0.latitude,
s1_0.longitude,
s1_0.updated_at 
from
favorite_store fs1_0 
left join
store s1_0 
on s1_0.store_id=fs1_0.store_id 
where
fs1_0.favorite_id=?
Hibernate: 
select
si1_0.store_id,
si1_0.store_image_id, …
```
> [feat] 족보 상세 조회 API 생성

- src/main/java/org/hankki/hankkiserver/api/store/service/HeartCommandService.java
- src/main/java/org/hankki/hankkiserver/api/store/service/response/HeartCreateResponse.java
- src/main/java/org/hankki/hankkiserver/api/store/service/response/HeartDeleteResponse.java
- src/main/java/org/hankki/hankkiserver/domain/heart/repository/HeartRepository.java
close #82 
- 좋아요 취소와 생성을 요청을 보낼 때, 그 응답값으로 해당 가게의 전체 좋아요 갯수도 함께 보내달라는 클라측의 요청이 있어 이를 반영하였습니다.
> [feat] 좋아요 전체 갯수 응답값 추가

- src/main/java/org/hankki/hankkiserver/api/store/parameter/PriceCategory.java
close #86 
- 주어진 명세와 같이 가격 뒤에 '원'을 추가했습니다.
> [fix] 가격정보 드롭다운 조회 응답 변경

- src/main/java/org/hankki/hankkiserver/api/store/service/HeartFinder.java
- src/main/java/org/hankki/hankkiserver/api/user/controller/UserController.java
- src/main/java/org/hankki/hankkiserver/api/user/service/UserQueryService.java
- src/main/java/org/hankki/hankkiserver/api/user/service/response/UserHeartedStoreListResponse.java
- src/main/java/org/hankki/hankkiserver/api/user/service/response/UserHeartedStoreViewResponse.java
- src/main/java/org/hankki/hankkiserver/domain/heart/repository/HeartRepository.java
close #60 
- 사용자가 좋아요한 가게의 정보들을 불러오는 api 입니다.
일단 fetch join으로 구현해보았는데, fetch join을 안써도 되는지 좀 더 고민해보겠습니다.
+ 정렬은 디자인 측에서 좋아요가 가장 최신에 추가된 가게가 맨 상단에 있었으면 좋겠다고 하여 기본키 값을 내림차순으로 정렬하였습니다.
```
Hibernate: 
select
h1_0.heart_id,
s1_0.store_id,
s1_0.category,
s1_0.created_at,
s1_0.heart_count,
i1_0.store_id,
i1_0.store_image_id,
i1_0.created_at,
i1_0.image_url,
s1_0.is_deleted,
s1_0.lowest_price,
s1_0.name,
s1_0.latitude,
s1_0.longitude,
s1_0.updated_at,
h1_0.user_id 
from
heart h1_0 
join
store s1_0 
on s1_0.store_id=h1_0.store_id 
join
store_image i1_0 
on s1_0.store_id=i1_0.store_id 
where
h1_0.user_id=? 
and s1_0.is_deleted=false 
order by
h1_0.heart_id desc
```
> [feat] 사용자가 좋아요를 한 가게들의 정보들을 불러오는 api

- src/main/java/org/hankki/hankkiserver/api/report/service/ReportFinder.java
- src/main/java/org/hankki/hankkiserver/api/user/controller/UserController.java
- src/main/java/org/hankki/hankkiserver/api/user/service/UserQueryService.java
- src/main/java/org/hankki/hankkiserver/api/user/service/response/UserStoreReportedResponse.java
- src/main/java/org/hankki/hankkiserver/api/user/service/response/UserStoresReportedGetResponse.java
- src/main/java/org/hankki/hankkiserver/domain/report/repository/ReportRepository.java
close #59 
- 마이페이지 - 사용자가 제보한 가게 API입니다.
###작성한 JPQL
사용자의 report를 FK값 userId로 찾고, 연관된 store와 storeImage를 fetch join으로 가져왔습니다. 정렬은 생성일 내림차순으로 했습니다. 
```java
@Query("select r from Report r join fetch r.store join fetch r.store.images where r.user.id = :userId and r.store.isDeleted = false order by r.createdAt desc")
List<Report> findAllByUserIdWithStoreAndStoreImage(@Param("userId") Long userId);
```
유저가 서로 다른 대학에 같은 가게를 제보했을 경우 가게가 중복으로 나오기 때문에 distinct()를 통해 중복제거를 해주었습니다. 
```java
@Transactional(readOnly = true)
public UserStoresReportedGetResponse findUserStoreReported(final Long userId) {
return UserStoresReportedGetResponse.of(reportFinder.findAllByUserId(userId).stream().map(Report::getStore).distinct().toList());
}
```
```sql
Hibernate: 
select
r1_0.report_id,
r1_0.created_at, …
```
> [feat] 마이페이지 - 사용자가 제보한 가게 API

- .gitignore
- build.gradle
- src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java
- src/main/java/org/hankki/hankkiserver/api/store/parameter/PriceCategory.java
- src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java
- src/main/java/org/hankki/hankkiserver/api/store/service/StoreQueryService.java
- src/main/java/org/hankki/hankkiserver/api/store/service/response/PinResponse.java
- src/main/java/org/hankki/hankkiserver/api/store/service/response/StorePinsResponse.java
- src/main/java/org/hankki/hankkiserver/api/store/service/response/StoreResponse.java
- src/main/java/org/hankki/hankkiserver/api/store/service/response/StoresResponse.java
- src/main/java/org/hankki/hankkiserver/api/user/service/response/UserStoreReportedResponse.java
- src/main/java/org/hankki/hankkiserver/domain/config/QueryDslConfig.java
- src/main/java/org/hankki/hankkiserver/domain/store/model/Store.java
- src/main/java/org/hankki/hankkiserver/domain/store/repository/CustomStoreRepository.java
- src/main/java/org/hankki/hankkiserver/domain/store/repository/CustomStoreRepositoryImpl.java
- src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreRepository.java
close #112 
- 지도뷰에서 핀 조회 및 식당 리스트 조회 api 구현했습니다.
- 동적 쿼리를 querydsl 도입했습니다.
- 식당과 대학교 중간 테이블은 n+1방지를 위해 fetch join했습니다.
- 컬렉션 페치조인은 두번을 할 수 없기에 storeImage는 @Batch를 사용하여 in 쿼리로 가져오도록 했습니다.
- 추후 리스트뷰에서는 페이징이 도입될 예정이기에 fetch join을 삭제할 수 있을 것 같습니다.
> [feat] 지도뷰 핀 조회 및 식당 리스트 조회 api 구현

- src/main/java/org/hankki/hankkiserver/api/store/service/response/StoreThumbnailResponse.java
close #120 
- 썸네일 조회시 이미지 url을 반환하도록 수정
- 컬렉션 페치조인(식당, 식당사진)을 하는 비용이나 단일 조회 쿼리 2방 날리는 비용이나 비슷할 거 같아서 굳이 컬렉션 fetch join을 하지는 않았습니다.
> [fix] 썸네일 조회시 이미지 url을 반환하도록 수정

- src/main/java/org/hankki/hankkiserver/api/auth/service/AuthService.java
close #139 
- 프로필 이미지가 로그인할 때마다 변경되는 이슈가 있습니다.
`loadOrCreateUser` 함수부분에서 탈퇴 후 재가입한 사람인지 로그아웃 후 재가입한 사람인지 구분하지 않고 map 안의 `updateUserInfo`함수가 항상 실행되어 로그인 할 때마다 프로필 이미지가 변경되었던 것 같습니다.
-> isRegistered를 추가적으로 함수 인자로 받아서 False일 경우 탈퇴 후 재가입한 사람, True일 경우 로그아웃한 사람으로 구분하여 함수를 나누었습니다.
> [fix] 프로필 이미지 변경 이슈 수정

- src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java
- src/main/java/org/hankki/hankkiserver/api/store/service/HeartDeleter.java
- src/main/java/org/hankki/hankkiserver/api/store/service/StoreCommandService.java
- src/main/java/org/hankki/hankkiserver/domain/heart/repository/HeartRepository.java
- src/main/java/org/hankki/hankkiserver/domain/store/model/Store.java
close #145 
- 식당 삭제 api (soft delete)
api 테스트 완료
soft delete 범위를 어디까지 가져갈 지 고민.. 
지금 식당이랑 연결된 테이블이 굉장히 많은데, 식당을 삭제하면 다른 테이블들에 연관된 값들도 삭제할 것인지
-> 지금은 제보자가 클릭 한번으로 삭제를 할 수 있는 구조라서 만약 다 삭제하도록 구현했을 때, 악덕 사용자가 정상적인 식당을 삭제했을 때, 복구가 힘들 것 같음
-> 그래서 지금은 일단 isDeleted만 true로 바뀌고 해당 식당아이디를 좋아요한 목록들까지만 삭제해주었는데 다른 부분들도 삭제해주어야할 지 고민입니다.
*** 
기획과 합의 결과, isDeleted만 true로 바꾸기로 하였습니다.
> [feat] 식당 삭제 api

- src/main/java/org/hankki/hankkiserver/api/auth/service/UserFinder.java
- src/main/java/org/hankki/hankkiserver/api/store/service/HeartCommandService.java
- src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java
close #148 
좋아요 생성 및 삭제 로직에서 부적절한 Store id값이 들어왔을 때 예외처리를 추가해주었습니다.
- User의 경우 Reference를 사용하면 쿼리가 나가지 않는다는 이점이 있어서 Reference 사용을 유지했습니다. 
(+ User까지 예외처리를 하기는 너무나 과하다고 생각)
- 별개로 위 경도 값으로 식당 검증하기로 결정해서 store 엔티티에 address 속성은 필요 없지 않나요?
> [refac] 좋아요 로직 예외처리 추가

- src/main/java/org/hankki/hankkiserver/api/advice/GlobalExceptionHandler.java
- src/main/java/org/hankki/hankkiserver/api/store/service/StoreCommandService.java
- src/main/java/org/hankki/hankkiserver/api/store/service/response/StoreResponse.java
- src/main/java/org/hankki/hankkiserver/api/store/service/response/StoreThumbnailResponse.java
- src/main/java/org/hankki/hankkiserver/common/code/StoreImageErrorCode.java
- src/main/java/org/hankki/hankkiserver/common/exception/BadGatewayException.java
close #156 
- 식당 썸네일 조회시 default이미지를 사용한다면 imageUrl을 null로 반환합니다.
- 식당 리스트 조회시 default이미지를 사용한다면 imageUrl을 null로 반환합니다.
- 식당 세부 조회에서는 빈리스트를 반환합니다 -> 로직 변경 없음
- 기본이미지를 서버에서 관리하지 않게 됨에 따라 식당 생성 로직에서 이미지가 업로드되지 않았다면 storeImage를 저장하지 않도록 변경했습니다.
> [fix] 기본 이미지 정책 변경에 따른 로직 수정

- src/main/java/org/hankki/hankkiserver/api/favorite/controller/FavoriteController.java
- src/main/java/org/hankki/hankkiserver/api/favorite/controller/request/FavoritePostRequest.java
- src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteCommandService.java
- src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteFinder.java
- src/main/java/org/hankki/hankkiserver/common/code/FavoriteErrorCode.java
- src/main/java/org/hankki/hankkiserver/domain/favorite/repository/FavoriteRepository.java
close #150 
- 족보 제목 중복 예외 처리
- 해시태그 [#일이삼사오육칠팔] 까지만 된다고 하여 max를 9로 지정
- where 절에 족보 제목 & 유저로 검색하는 로직 추가
- 테스트완료
```json
{
"code": 409,
"message": "이미 존재하는 족보 제목입니다."
}
```
> [feat] 족보 제목 중복 예외 처리

- src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java
- src/main/java/org/hankki/hankkiserver/api/store/controller/request/StoreDuplicateValidationRequest.java
- src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java
- src/main/java/org/hankki/hankkiserver/api/store/service/StoreQueryService.java
- src/main/java/org/hankki/hankkiserver/api/store/service/command/StoreValidationCommand.java
- src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreRepository.java
close #168 
- 같은 건물 다른 층에 위치한 식당의 경우, 위 경도 값이 일치하는 문제가 발생하여 식당 이름을 검증 조건을 추가합니다.
추가적으로 식당 삭제할 때 어떻게 처리할지에 대해 기획분들께 물어봤는데 릴리즈할 때까지 시간이 얼마 남지 않아 식당 삭제 제보가 들어오고 나서 재제보하는 것을 막지 않는다고 합니다. 때문에 식당 등록 로직에서 검증 로직 빼야할 것 같습니다. 
https://github.com/Team-Hankki/hankki-server/blob/e3f871d155ac02d23c3bf68b5e7bf17bc583d8ac/src/main/java/org/hankki/hankkiserver/api/store/service/StoreCommandService.java#L50-L52
이 부분 삭제해야함다. (지금 저 로직이 포함되어 있으면 삭제된 식당에 대한 재제보가 막히게돼요!)
> [fix] 식당 제보 validation 검증 조건 추가 

- src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteQueryService.java
- src/main/java/org/hankki/hankkiserver/api/favoritestore/service/FavoriteStoreFinder.java
- src/main/java/org/hankki/hankkiserver/api/store/service/StoreFinder.java
- src/main/java/org/hankki/hankkiserver/domain/favoritestore/repository/FavoriteStoreRepository.java
- src/main/java/org/hankki/hankkiserver/domain/store/repository/StoreRepository.java
close #166 
- 족보 상세보기에서 식당 정렬순 족보에 추가한 순으로 변경
1. Favorite과 FavoriteStore [left join fetch]로 가져옴 
(족보에 가게 있다면)
2. favoriestore와 store 그냥 join 함 - 이미 1번으로 인해 FavoriteStore 영속성에 있으므로 굳이 fetch join 할 필요없음
```java
@Query("select s from Store s join FavoriteStore fs on s.id = fs.store.id where fs in :favoriteStores and s.isDeleted = false order by fs.id desc ")
List<Store> findAllByIdsAndIsDeletedIsFalseOrderByFavoriteStoreId(@Param("favoriteStores") List<FavoriteStore> favoriteStores);
```
3. store_image는 batch로 in쿼리로 가져옴
<족보에 가게 있을 경우>
```sql
Hibernate: 
select
f1_0.favorite_id,
f1_0.created_at,
f1_0.detail,
fs1_0.favorite_id,
fs1_0.favorite_store_id,
fs1_0.store_id,
f1_0.image_type,
f1_0.name,
f1_0.updated_at,
f1_0.user_id 
from
favorite f1_0 
left join
favorite_store fs1_0 
on …
```
> [feat] 족보 상세보기에서 식당 정렬순 족보에 추가한 순으로 변경

- src/main/java/org/hankki/hankkiserver/domain/store/model/StoreImage.java
close #182 
- 255자를 넘는 url이 있어 타입 TEXT로 변경했습니다.
> [fix] image_url 컬럼 타입 TEXT로 변경

- src/main/java/org/hankki/hankkiserver/api/advice/GlobalExceptionHandler.java
- src/main/java/org/hankki/hankkiserver/api/menu/controller/MenuController.java
- src/main/java/org/hankki/hankkiserver/api/menu/service/DeletedMenuUpdater.java
- src/main/java/org/hankki/hankkiserver/api/menu/service/MenuCommandService.java
- src/main/java/org/hankki/hankkiserver/api/menu/service/MenuFinder.java
- src/main/java/org/hankki/hankkiserver/api/menu/service/command/MenuDeleteCommand.java
- src/main/java/org/hankki/hankkiserver/api/menu/service/response/MenuGetResponse.java
- src/main/java/org/hankki/hankkiserver/api/menu/service/response/MenusGetResponse.java
- src/main/java/org/hankki/hankkiserver/api/store/service/StoreUpdater.java
- src/main/java/org/hankki/hankkiserver/domain/menu/model/DeletedMenu.java
- src/main/java/org/hankki/hankkiserver/domain/menu/repository/DeletedMenuRepository.java
- src/main/java/org/hankki/hankkiserver/domain/menu/repository/MenuRepository.java
close #217 
- 해당 식당에 존재하는 메뉴 목록 불러오는 API
API 테스트 완료
> [feat] 식당 Id로 메뉴 목록 불러오기

- src/main/java/org/hankki/hankkiserver/api/favorite/controller/FavoriteController.java
- src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteQueryService.java
- src/main/java/org/hankki/hankkiserver/api/favorite/service/response/FavoriteNicknameGetResponse.java
- src/main/java/org/hankki/hankkiserver/api/favorite/service/response/FavoriteUserNicknameGetResponse.java
close #230 
- 족보 주인 닉네임 조회 API입니다. 
- favoriteId를 통해 족보 주인의 ID(FK)를, 그 ID로 UserInfo의 nickname을 조회합니다. 
```sql
Hibernate: 
select
f1_0.favorite_id,
f1_0.created_at,
f1_0.detail,
f1_0.image_type,
f1_0.name,
f1_0.updated_at,
f1_0.user_id 
from
favorite f1_0 
where
f1_0.favorite_id=?
Hibernate: 
select
ui1_0.user_info_id,
ui1_0.nickname,
ui1_0.refresh_token,
ui1_0.user_id 
from
user_info ui1_0 
where
ui1_0.user_id=?
```
> [feat] 족보 주인 닉네임 조회 API

- src/main/java/org/hankki/hankkiserver/api/favorite/controller/FavoriteController.java
- src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteQueryService.java
- src/main/java/org/hankki/hankkiserver/api/favorite/service/response/FavoriteSharedGetResponse.java
- src/main/java/org/hankki/hankkiserver/auth/config/SecurityConfig.java
close #232 
- 족보 공유 관련 API 분리 - 시큐리티 whiteList에 추가
- 족보 상세보기 API와 공유 족보 상세보기 API를 분리했습니다.
> [feat] 족보 공유 관련 API 분리, 시큐리티 whiteList에 추가

- src/main/java/org/hankki/hankkiserver/api/favorite/service/FavoriteCommandService.java
close #238 
- 공유족보에서 imageType 바뀌지 않는 문제 fix
상대방 FavoriteStore를 조회한 쿼리 반환값에서 size()를 통해 업데이트하게 했습니다.
> [fix] 공유족보 생성 시 imageType 바뀌지 않는 문제 fix

- src/main/java/org/hankki/hankkiserver/api/advice/ResponseAdvice.java
- src/main/java/org/hankki/hankkiserver/api/auth/controller/AuthController.java
- src/main/java/org/hankki/hankkiserver/api/common/PriceCategoryConverter.java
- src/main/java/org/hankki/hankkiserver/api/common/UserIdArgumentResolver.java
- src/main/java/org/hankki/hankkiserver/api/common/advice/GlobalExceptionHandler.java
- src/main/java/org/hankki/hankkiserver/api/common/advice/ResponseAdvice.java
- src/main/java/org/hankki/hankkiserver/api/common/annotation/UserId.java
- src/main/java/org/hankki/hankkiserver/api/config/WebConfig.java
- src/main/java/org/hankki/hankkiserver/api/favorite/controller/FavoriteController.java
- src/main/java/org/hankki/hankkiserver/api/menu/controller/MenuController.java
- src/main/java/org/hankki/hankkiserver/api/store/controller/StoreController.java
- src/main/java/org/hankki/hankkiserver/api/store/parameter/PriceCategory.java
- src/main/java/org/hankki/hankkiserver/api/universitystore/controller/UniversityStoreController.java
- src/main/java/org/hankki/hankkiserver/api/user/controller/UserController.java
- src/main/java/org/hankki/hankkiserver/domain/store/model/StoreCategory.java
close #241 
- 가격대 전체 카테고리 추가
- 이미지 카테고리 정렬
> [feat] 가격대 전체 카테고리 추가

- src/main/java/org/hankki/hankkiserver/api/menu/service/MenuCommandService.java
close #243 
- 본래 `validateMenuConflict`함수를 실행할 때마다 select 쿼리가 발생하던 것을, 처음부터 모든 메뉴를 가져오고(select 쿼리 1번), list에서 stream을 돌면서 판단하도록 수정했습니다.
엄청 간단한 수정 사항입니다.
> [refac] 메뉴 추가 시 발생 쿼리문 개선

- build.gradle
- src/main/java/org/hankki/hankkiserver/api/common/annotation/Retry.java
- src/main/java/org/hankki/hankkiserver/api/store/aspect/RetryAspect.java
- src/main/java/org/hankki/hankkiserver/api/store/service/HeartCommandService.java
- src/main/java/org/hankki/hankkiserver/common/aspect/RetryAspect.java
- src/main/java/org/hankki/hankkiserver/common/code/HeartErrorCode.java
- src/main/java/org/hankki/hankkiserver/domain/store/model/Store.java
close #248 
- 프레임워크를 사용하지 않고, aop 로직 구현했습니다.
테스트 완료
RetryAspect 클래스 위치를 api.common으로 옮길지 지금처럼 store 패키지 하위에 위치시킬지 고민입니다
> [fix] 좋아요 수 동시성 이슈 처리

- README.md
- build.gradle
close #254 
- 데이터베이스를 MySQL로 이전합니다.
- 서브모듈을 업데이트했습니다.
> [feat] 데이터베이스를 MySQL로 이전
